<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali</name>
   <tag></tag>
   <elementGuidId>2809c33e-c84d-4948-9102-0ba7f7513d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ed3a371-2b9b-4bdf-8902-4953f5c7e86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-cta btn-back flex justify-center sm:w-auto  w-full </value>
      <webElementGuid>e70d4368-52c9-417e-bf58-23c21091c3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eae0a1ce-b46c-4d91-b71c-3feb34ee81ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>d9f579af-8f19-4c33-beb3-6f870cbe6386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[2]/div[@class=&quot;flex min-h-screen&quot;]/div[@class=&quot;pt-8 mx-32 w-3/5&quot;]/div[@class=&quot;mt-6&quot;]/div[@class=&quot;px-4 py-4 fixed bottom-0 left-0 z-10 sm:z-0 flex justify-center w-full bg-white border-t-thin border-gray-100 sm:relative sm:border-none sm:bg-transparent sm:w-auto sm:bottom-auto sm:top-auto sm:mt-8 sm:px-20&quot;]/button[@class=&quot;btn btn-cta btn-back flex justify-center sm:w-auto  w-full&quot;]</value>
      <webElementGuid>720e6d90-5d53-440f-97df-81b0810fdd07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>63142209-0fb7-44d4-858b-68306581121a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div[3]/button</value>
      <webElementGuid>c687351d-ebff-480e-ab94-24c3fcb41fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('4. Pilih ', '&quot;', 'Virtual Account Billing', '&quot;', '')])[1]/following::button[1]</value>
      <webElementGuid>4c5f28fb-fa61-4e3c-9e16-9434785d2226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='woocommerce-xendit-366'])[1]/preceding::button[1]</value>
      <webElementGuid>9d36e28d-63ed-4d81-9a1b-30cb680f49d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>fd653898-e16a-40bb-93ca-305e74b602b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>a63fcb21-acb8-45ef-9a9c-1bc19144683f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
