<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Deskripsi</name>
   <tag></tag>
   <elementGuidId>e865d5ca-e3db-47d4-ab34-ec164d1f25bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.font-bold.uppercase.leading-4.pb-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div[2]/div[2]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Deskripsi' or . = 'Deskripsi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c0eaae40-055e-4186-bf35-caa4666f3f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-bold uppercase leading-4 pb-2</value>
      <webElementGuid>654da3a6-fa27-44a8-90a5-d70fd2af21a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deskripsi</value>
      <webElementGuid>53559d5d-a721-45f2-a553-a3abaee10d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[2]/div[@class=&quot;flex min-h-screen&quot;]/div[@class=&quot;pt-8 px-16 w-2/5 bg-gray-100 bg-opacity-50 divide-y divide-gray-200 divide-solid&quot;]/div[@class=&quot;pb-2&quot;]/div[@class=&quot;flex p-4&quot;]/div[2]/p[@class=&quot;font-bold uppercase leading-4 pb-2&quot;]</value>
      <webElementGuid>429116e2-9e82-4675-8082-cd20c92ea4e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div[2]/div[2]/p</value>
      <webElementGuid>b2b92b3c-b97e-42ea-b5f4-cdf0126975df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='woocommerce-xendit-366'])[1]/following::p[1]</value>
      <webElementGuid>000b1dbe-6cf5-443f-a3af-d24dd1a1ffa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='woocommerce-xendit-366'])[2]/preceding::p[1]</value>
      <webElementGuid>bd303b06-edc5-4d2d-a5cf-fa55cf9d107d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deskripsi']/parent::*</value>
      <webElementGuid>0cf3b598-a7d0-4a99-b89f-56cc599812d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>8827acbf-b266-4d16-8eb9-03bbb071aa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Deskripsi' or . = 'Deskripsi')]</value>
      <webElementGuid>52c0eab9-c726-4865-91c9-aa32fb09b010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
