<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter a valid email address</name>
   <tag></tag>
   <elementGuidId>d783f18e-4e97-40d1-a194-af5578201352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='wpforms-291-field_1-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wpforms-291-field_1-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2826d69a-bb97-477c-b30b-96d3519a0b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-291-field_1-error</value>
      <webElementGuid>c1691947-7fe2-4b17-9f35-229224ed64e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-error</value>
      <webElementGuid>c4bbfa89-5f80-478d-8ada-c436a8c86fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>wpforms-291-field_1</value>
      <webElementGuid>c628df4e-0690-43bc-9cad-fc43ced57adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid email address.</value>
      <webElementGuid>12c110de-71f8-423e-8753-0f349a741fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-291-field_1-error&quot;)</value>
      <webElementGuid>b2ed4acf-5114-4d70-a936-d3212172e6a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='wpforms-291-field_1-error']</value>
      <webElementGuid>90490051-4236-489f-8e8c-104687fa16de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-291-field_1-container']/label[2]</value>
      <webElementGuid>33a13051-5cc0-4027-95e0-96b9e73f929f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[1]</value>
      <webElementGuid>765020d9-ddc6-4832-bb3c-1b1aa45a5fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>f9111eec-72d6-4603-8fb2-233e93418688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地図&amp;アクセス方法'])[1]/preceding::label[1]</value>
      <webElementGuid>52c56fb3-bd31-45c9-8ed5-589f6d67a2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter a valid email address.']/parent::*</value>
      <webElementGuid>1e611492-5757-4613-956a-58729a54a385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>3452b37b-c07e-4de9-9071-3eded29063ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'wpforms-291-field_1-error' and (text() = 'Please enter a valid email address.' or . = 'Please enter a valid email address.')]</value>
      <webElementGuid>6e37fdcd-8ab3-4010-b676-997a4b1dd7db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
