<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Payment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4a1e9ffd-d8d0-4149-9be3-0d7c94459c3b</testSuiteGuid>
   <testCaseLink>
      <guid>807f3876-2892-4a62-9eae-14e687bb6bfd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/Add new payee</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26c8a77d-56d7-400d-b6a6-1d510dd33d4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>874e4d46-0277-4675-be94-44060f561798</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/Make payment 01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>235477c7-346a-443c-b1a7-b97221cee9d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d2d1f19-dd31-4503-85fb-5c47c45cd817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/Make payment 02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e8da72f-e34a-447b-a061-921b33a0b6c3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
