<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rp20 Rp18</name>
   <tag></tag>
   <elementGuidId>18bfe6b7-0ba9-4410-92a6-ff5a7fb663f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-238']/div/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9ec2f54a-0a6d-4248-864f-985fbc5fbda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>8f8b0e61-7a43-4210-9f42-82a58a1dd114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp20 Rp18</value>
      <webElementGuid>72982ef7-b4b7-4ec7-a875-16430b42b982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-238&quot;)/div[@class=&quot;product_infos&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-5 columns&quot;]/div[@class=&quot;summary entry-summary&quot;]/p[@class=&quot;price&quot;]</value>
      <webElementGuid>0f8ef431-ead0-4457-85fd-b13b28ac8637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-238']/div/div/div[2]/div/p</value>
      <webElementGuid>7c391bc4-405f-4d01-abf9-48817a372d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beanie'])[2]/following::p[1]</value>
      <webElementGuid>3fb17f4d-3e7b-4f41-a02e-2490fb838fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::p[1]</value>
      <webElementGuid>7c32fc27-d247-4e0f-ba1b-72d3ff85bdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>8141972b-95d5-4c05-b7bd-8ba56f7c7861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rp20 Rp18' or . = 'Rp20 Rp18')]</value>
      <webElementGuid>034bb92e-4e91-4b7c-8b22-6aa50ce6de85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
