<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Qty box</name>
   <tag></tag>
   <elementGuidId>68b4ec68-8dda-41d4-b54b-fb7fca17e1d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity_62c6b2ff0c74d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_62c6b2ff0c74d']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @class = 'input-text qty text' and @name = 'quantity' and @title = 'Qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f495b97-f2ea-4e8f-98f7-72ca78d522e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>893db4ab-9aff-4922-8fe7-9a7c55d250c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_62c6b2ff0c74d</value>
      <webElementGuid>f7f9de7f-fccb-44d3-aa8b-44a936261f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>2f5ab309-305c-4363-9f70-af720676e1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>26ee1892-d0f1-4207-b3a8-b9c722afd155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f0fadf69-f177-422a-855d-3e4ff2c6536a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>f5690b27-1120-4862-abc9-b215b0d4d879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fd7dc8b2-7466-409d-8427-c75fb08672eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>ee53bf2e-85c7-40a8-957d-10fd7dd6e32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8cc56539-6ba7-4ee1-9178-7fb74787820e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>f5566891-e852-4c9c-99c1-d626f2436ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0a47ab94-4d84-409e-9e89-298d185a57e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_62c6b2ff0c74d&quot;)</value>
      <webElementGuid>709e7ac5-0bff-435f-b192-c2f3193639df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_62c6b2ff0c74d']</value>
      <webElementGuid>c1dca4bd-2bf5-4627-ac70-b45c65175ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-240']/div/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>cb2ab844-4c2f-40db-9564-3eb830662ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>944235cf-6da6-4220-955d-2da57a28330a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_62c6b2ff0c74d' and @name = 'quantity' and @title = 'Qty']</value>
      <webElementGuid>9f4acd8f-f062-4960-b2b3-ca94079cd810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
