<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password</name>
   <tag></tag>
   <elementGuidId>e38d0ba6-50e7-4bb3-a6e3-9f3bdfbc4a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_user_password-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirm_user_password-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00b627bf-7e51-4d1d-a93d-013bbf942e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid um-validate-not-matched</value>
      <webElementGuid>37805c00-4a02-4804-b6f2-2a66af77e3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c1e5ba3f-ea52-46a8-94ca-30ae81ab850e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>a47e35ac-b259-4461-8903-7d857ea9c453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>1d5d86e5-7a4b-4a0c-bdf2-59acbf57eec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>0dfd0a1e-bb60-4a28-99c9-6a9cd81a6ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>confirm_user_password</value>
      <webElementGuid>dc8e14bf-1146-4005-a31b-c443228b759f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_user_password-297&quot;)</value>
      <webElementGuid>d3d0ca8d-be25-4432-92f4-3ddaa9c8e805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_user_password-297']</value>
      <webElementGuid>7a6033ee-5eab-4931-bb05-08ba0c58ad19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_confirm_user_password']/div[2]/input</value>
      <webElementGuid>9a790a4c-2d41-4f89-a530-3894ee9a9473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>d130d269-3677-48ed-9cb2-e120e0f45be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_user_password-297' and @id = 'confirm_user_password-297' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>2ecc172d-66f5-4ea6-be1a-e7aebe266639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
