<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Remove product</name>
   <tag></tag>
   <elementGuidId>4d92f323-2faf-400c-91a7-b7c79b729ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-53']/div/div/form/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.remove</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'remove' and @aria-label = 'Remove this item' and (text() = '×' or . = '×')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d0ff050a-12e6-41f5-878f-91dd19e67945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/cart-2/?remove_item=555d6702c950ecb729a966504af0a635&amp;_wpnonce=4b8ab0f44f</value>
      <webElementGuid>46224d99-1c7d-4ab2-bf6b-4111f65a3f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove</value>
      <webElementGuid>991350ed-7a51-452a-a5e3-12987a214da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove this item</value>
      <webElementGuid>104cd58d-f82b-4e77-8c0d-7756ace55135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>239</value>
      <webElementGuid>11be8d43-68a9-42a7-8703-e358c663b3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>woo-belt</value>
      <webElementGuid>d2b6a4e3-4439-447e-ad97-244c685d421b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>527e2153-1e96-4c65-bdf1-da0194aa0898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-53&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-remove&quot;]/a[@class=&quot;remove&quot;]</value>
      <webElementGuid>877edb36-de98-42e4-8c61-a8f228f501b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-53']/div/div/form/table/tbody/tr/td/a</value>
      <webElementGuid>0ccc19c8-6578-41f8-bec2-7e75577fad29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'×')]</value>
      <webElementGuid>6ccf0790-17a5-4516-9399-c2f9dde266ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/following::a[1]</value>
      <webElementGuid>cdca6ffa-e6c6-4708-80a7-cf7fc2852174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::a[1]</value>
      <webElementGuid>c5fce562-9aa9-4d31-9ed1-057084756649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belt'])[1]/preceding::a[2]</value>
      <webElementGuid>f3ea2a5e-7bb9-4a17-9b47-4ab64b59a589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[4]/preceding::a[3]</value>
      <webElementGuid>9a22370b-b191-44b4-9f6b-0565ad2c0c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>b3a0107c-ccbc-4896-9797-913aa4ff2115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kotakoki.wijaysali.my.id/cart-2/?remove_item=555d6702c950ecb729a966504af0a635&amp;_wpnonce=4b8ab0f44f')]</value>
      <webElementGuid>d833a99a-4a45-4156-a925-c2c97befed6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>81f27fb6-6edd-4f7b-93a1-1a34865d9df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kotakoki.wijaysali.my.id/cart-2/?remove_item=555d6702c950ecb729a966504af0a635&amp;_wpnonce=4b8ab0f44f' and (text() = '×' or . = '×')]</value>
      <webElementGuid>24708996-d3b8-4e98-ab72-82dfbbce486d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
