<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Your order</name>
   <tag></tag>
   <elementGuidId>51078b3d-2494-4884-8e4f-242c904c6165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_review_heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='order_review_heading']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'order_review_heading' and (text() = 'Your order' or . = 'Your order')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6642a9a9-f662-4801-94b6-a118f04d07a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_review_heading</value>
      <webElementGuid>0651e71e-0f05-4e4e-a0bf-76781ed7739a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your order</value>
      <webElementGuid>f27da4c0-5cb4-45e3-a772-6ca15b432224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_review_heading&quot;)</value>
      <webElementGuid>bbd52b9e-2909-466a-a5fc-b1f79ca85ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='order_review_heading']</value>
      <webElementGuid>7c181ee3-0453-465a-884b-b4a3e100bcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-54']/div/div/form[2]/h3</value>
      <webElementGuid>cf72713c-1f5d-48e7-85a9-ba32ce8a5c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[3]/following::h3[1]</value>
      <webElementGuid>1adb4352-3cd9-4ca5-a171-7d9c51a89099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/preceding::h3[1]</value>
      <webElementGuid>a43f5f3e-05fc-4133-ae42-b89b5fd01a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/preceding::h3[1]</value>
      <webElementGuid>ce918caf-bc7a-45ee-b843-64c3bb271f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your order']/parent::*</value>
      <webElementGuid>7552957e-c238-44cc-84c1-978020e9ab00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/h3</value>
      <webElementGuid>1001a441-446f-4836-8779-cd56e5942171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'order_review_heading' and (text() = 'Your order' or . = 'Your order')]</value>
      <webElementGuid>5813dbc6-a8e8-4adb-845b-3c015a6254ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
