<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkaja</name>
   <tag></tag>
   <elementGuidId>768765f4-447d-4cb8-a3a4-92da40878ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_xendit_linkaja']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_method_xendit_linkaja</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>657d8977-b4ae-4520-93e6-7bd92288794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_xendit_linkaja</value>
      <webElementGuid>f4d358ea-dd53-4d36-bd8a-0fff1bcf2489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f69a8e82-4f9f-4249-aae0-227bbbc4f36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>80c32931-d1fb-472b-ac12-08a63551064e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>7ea622be-9569-472f-ba76-8b264b3d962c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>xendit_linkaja</value>
      <webElementGuid>2583f83f-2031-4212-b2d6-e19bbb4c1708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_xendit_linkaja&quot;)</value>
      <webElementGuid>bffac0b5-ec4c-4f53-b0d2-578f8e11b139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_xendit_linkaja']</value>
      <webElementGuid>74e88684-a76e-4325-be56-5fe8718e7567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[13]/input</value>
      <webElementGuid>f7a4c7a9-c630-41cb-b769-870b7c7c1bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/input</value>
      <webElementGuid>be10e244-ae3a-4656-988a-ac652e53beae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_xendit_linkaja' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>9173942d-6d56-47c9-9194-98d486aadd93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
