<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Last name</name>
   <tag></tag>
   <elementGuidId>1a67c659-aad7-4fe0-8ff8-73c9f416375f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_last_name_field']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_last_name_field > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cf532d80-887e-47e5-9f7a-c8de370987ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>235b57ff-0901-44ee-a4ea-e99bd831538b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last name *</value>
      <webElementGuid>bb859744-98bd-48b6-9d24-0498d788ff3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_last_name_field&quot;)/label[1]</value>
      <webElementGuid>6cd486bc-ed14-4062-837a-82e24e6f0821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_last_name_field']/label</value>
      <webElementGuid>51cf1872-5085-4f7d-806a-acbe3a2275f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[1]</value>
      <webElementGuid>7f0d97a9-f7b0-4466-8f8b-1d907e0098af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/label</value>
      <webElementGuid>32090de9-2d31-4534-a2dc-a70c124fc4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Last name *' or . = 'Last name *')]</value>
      <webElementGuid>5ad6624c-c7f6-475d-ba1d-b0362f00d604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
