<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Postcode  ZIP</name>
   <tag></tag>
   <elementGuidId>390ec437-3f38-4d87-9d2a-47a7a0027fe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_postcode_field']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_postcode_field > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bb19c8cd-0578-440a-b106-108b8255a4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>5b61ca49-65fa-4099-a8cc-de77008fd142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postcode / ZIP *</value>
      <webElementGuid>992e0957-29db-4bfd-a899-dc3f7ab1fe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_postcode_field&quot;)/label[1]</value>
      <webElementGuid>3583eaa5-20e6-4d2a-95bf-0b497e06c81b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_postcode_field']/label</value>
      <webElementGuid>f81bf68b-8d2d-4810-8025-74810c840a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banten'])[2]/following::label[1]</value>
      <webElementGuid>badfff6b-71a7-4e0a-863a-f59ca846ad7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::label[1]</value>
      <webElementGuid>76044076-7097-43ba-9dee-d8d731a187f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Postcode / ZIP']/parent::*</value>
      <webElementGuid>1a68924b-46df-4e72-b2ea-4fd0812b9fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]/label</value>
      <webElementGuid>15433683-2dd9-4bc3-bcdb-e31931691808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Postcode / ZIP *' or . = 'Postcode / ZIP *')]</value>
      <webElementGuid>c5025248-7d74-419b-8821-ccff4fcdf0d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
