<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Company name(optional)</name>
   <tag></tag>
   <elementGuidId>ee873772-9ae2-412b-a864-5c4eeaafce26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_company_field']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_company_field > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c799f893-d949-4a66-8f5f-fb864a3d260b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>cdb07d9b-e92d-4b12-b161-e39a28b5c974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company name (optional)</value>
      <webElementGuid>a75d6944-26c1-43e8-90c1-7f4c27275763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_company_field&quot;)/label[1]</value>
      <webElementGuid>571f57a6-5de7-41b0-9c50-82722ac70cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_company_field']/label</value>
      <webElementGuid>3ec815aa-647e-4da7-85a1-f819a5672700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[1]</value>
      <webElementGuid>34478e7c-30a8-454b-a319-c3155d36b083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/label</value>
      <webElementGuid>38db3931-d763-4fbf-8be1-f002d39b6b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Company name (optional)' or . = 'Company name (optional)')]</value>
      <webElementGuid>e5c9b1e1-3917-4aac-b7f6-041b92c70de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
