<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Phone</name>
   <tag></tag>
   <elementGuidId>cf106737-d10e-43e3-a9f4-7637a7ab9994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_phone_field']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_phone_field > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c26334ea-327b-4267-84a3-8a358523a655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>16f1ff5b-8b62-46dd-9b84-b4337e0bc483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone *</value>
      <webElementGuid>b5e7d0ec-0914-4430-983c-ea83ba122db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_phone_field&quot;)/label[1]</value>
      <webElementGuid>af7e6826-fc41-44f8-9822-b8c1c3dc6bf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_phone_field']/label</value>
      <webElementGuid>3ceb2f5d-6ab9-47c2-ade1-dec94663b424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::label[1]</value>
      <webElementGuid>7ad15497-c49d-48ef-8a89-9eebc605112a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/label</value>
      <webElementGuid>fb5301b9-24dc-430b-ab7e-39e42ed2917d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Phone *' or . = 'Phone *')]</value>
      <webElementGuid>28853d5b-c977-4c91-ad7b-694f241ea147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
