<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submit newsletter</name>
   <tag></tag>
   <elementGuidId>7f3e026d-11c8-4c71-9e0c-58d7ef38c077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-submit-291</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='wpforms-submit-291']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;wpforms-submit-291&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff0fadaa-8ae3-4916-90a2-58d1f28d9e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b2eab855-1888-4f1d-9e2d-96624cab7061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[submit]</value>
      <webElementGuid>c0bf1a25-61cc-40a4-be6f-840dae2aadaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-submit-291</value>
      <webElementGuid>697ba293-2afa-4359-ad6e-3ac1f64b165f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-submit</value>
      <webElementGuid>0bcb91fa-a6ad-46be-88fe-ac8b5ededebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alt-text</name>
      <type>Main</type>
      <value>Sending...</value>
      <webElementGuid>399af38f-88b0-485b-aa60-bfc6db883bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-submit-text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>ddd9eadb-5b0a-4c63-b311-5fbfa503a322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>8144d210-0a53-437b-9c85-b8ee9c1a658e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>wpforms-submit</value>
      <webElementGuid>34b312bd-7395-48c4-9d38-062f6dbb3ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>f83abd55-aa66-4660-a326-046b96abdc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-submit-291&quot;)</value>
      <webElementGuid>a58a7a6f-b5b7-46f2-b3a6-d709f25f7baa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='wpforms-submit-291']</value>
      <webElementGuid>b5e10578-332b-4bf9-b0e3-c40a0004c777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='wpforms-form-291']/div[2]/button</value>
      <webElementGuid>aa6ee3fb-36b0-47fb-9672-bb89bbb96431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>78f30a78-3f73-4140-8c71-66f44c749d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地図&amp;アクセス方法'])[1]/preceding::button[1]</value>
      <webElementGuid>82432382-74d9-498f-8f8d-0b9be3d18934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせ'])[1]/preceding::button[1]</value>
      <webElementGuid>3300a32d-0384-40fb-8a29-f869a00438a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>d2da40af-c675-48b6-be2e-a81c3a527e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>08043584-0e00-40e2-8358-8b1fb70e0e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'wpforms[submit]' and @id = 'wpforms-submit-291' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>fe3c81f5-5101-4558-85f7-9abccfdc8da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
