<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_newsletter</name>
   <tag></tag>
   <elementGuidId>b4ac8cc4-9aa8-42d7-8a17-db4ca33bc3c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-291-field_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-291-field_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;wpforms-291-field_1&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>642c4057-e7cd-4dfc-8d2b-9cfbce3b7925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>48eb7597-5b23-4f4b-b931-f691a25bbeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-291-field_1</value>
      <webElementGuid>d1284383-a6dd-4cf4-85b8-fcbd89304e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required</value>
      <webElementGuid>016313ad-7ae9-4f04-91e4-1b7dee577ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][1]</value>
      <webElementGuid>45400e35-3814-456f-bfe1-fef0cbcbc508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-291-field_1&quot;)</value>
      <webElementGuid>760d20ef-9e2b-431e-b71e-84f862d9c95b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-291-field_1']</value>
      <webElementGuid>67e8db4c-48c3-4024-b25e-e77ef5029d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-291-field_1-container']/input</value>
      <webElementGuid>8a045698-9e61-4236-b997-4aa50b7e254d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>5de2f874-a5f3-43a8-8398-3c987fcd9392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'wpforms-291-field_1' and @name = 'wpforms[fields][1]']</value>
      <webElementGuid>efed0020-0125-41c9-874e-5327933f0588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
