<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>japan_1</name>
   <tag></tag>
   <elementGuidId>d3025b68-b3f5-4773-a9dc-fe80f35a8f64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5 > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='text-4']/div/h5/strong</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;text-4&quot;)/div[@class=&quot;textwidget&quot;]/h5[1]/strong[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>34a37079-fab8-4caf-af25-d7efebf0ec9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>地図&amp;アクセス方法</value>
      <webElementGuid>6432788b-49a6-4586-906d-721d6be07846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-4&quot;)/div[@class=&quot;textwidget&quot;]/h5[1]/strong[1]</value>
      <webElementGuid>596600e3-8f1e-4c1c-a5b6-13b3201d92c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='text-4']/div/h5/strong</value>
      <webElementGuid>529e4148-6c6f-49cc-9dfe-df81e29905a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::strong[2]</value>
      <webElementGuid>ed44830a-42f0-43fc-83f7-c64018250a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[1]/following::strong[2]</value>
      <webElementGuid>5efc0bbd-bf10-4533-be86-3a6f88568b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせ'])[1]/preceding::strong[1]</value>
      <webElementGuid>05cfb966-01b6-4c99-b682-30750d008529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2022. Powered by WS Lab'])[1]/preceding::strong[2]</value>
      <webElementGuid>e4689fba-d32b-448f-ad7e-62a62d974a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='地図&amp;アクセス方法']/parent::*</value>
      <webElementGuid>481be785-77a8-4ff4-b09b-95165fb6dc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/strong</value>
      <webElementGuid>8e6e9f8f-22fc-4792-b0b6-d97bb0ce4bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '地図&amp;アクセス方法' or . = '地図&amp;アクセス方法')]</value>
      <webElementGuid>b98d0e03-b5f9-4cef-9dfb-8df8738abaf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
