<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>japan_2</name>
   <tag></tag>
   <elementGuidId>5d4a0b16-6cc7-47fe-8b56-6aa801edeffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.h4 > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='text-3']/div/div/h3/strong</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;text-3&quot;)/div[@class=&quot;textwidget&quot;]/div[@class=&quot;grid__item post-large--one-quarter medium--one-half&quot;]/h3[@class=&quot;h4&quot;]/strong[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>6b89fc12-1c58-4fa8-a161-22f0cab4271a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>お問い合わせ</value>
      <webElementGuid>9aed017f-638e-43a2-816f-5bc46b65ea68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-3&quot;)/div[@class=&quot;textwidget&quot;]/div[@class=&quot;grid__item post-large--one-quarter medium--one-half&quot;]/h3[@class=&quot;h4&quot;]/strong[1]</value>
      <webElementGuid>e8a95878-1d9b-4b19-ad60-a6f038cb5941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='text-3']/div/div/h3/strong</value>
      <webElementGuid>336f3290-3b3c-4db0-993a-05204a635080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地図&amp;アクセス方法'])[1]/following::strong[1]</value>
      <webElementGuid>21ce10fa-1230-4c4f-9df6-1c0e28f28229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::strong[3]</value>
      <webElementGuid>e84bfe67-2546-4a85-9ef8-47c48e54e4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2022. Powered by WS Lab'])[1]/preceding::strong[1]</value>
      <webElementGuid>3ee17a25-6c76-4dff-a114-435c4e74ffce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::strong[1]</value>
      <webElementGuid>4feb8068-7b56-4c74-8661-f1830e5cbc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='お問い合わせ']/parent::*</value>
      <webElementGuid>840acb0b-3908-40ae-b2c4-9d5acf989440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/h3/strong</value>
      <webElementGuid>d6b87845-3732-41f0-94c3-c3c255daccf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'お問い合わせ' or . = 'お問い合わせ')]</value>
      <webElementGuid>f7c50952-5937-4d7c-b7db-0f1a71704b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
