<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_qty</name>
   <tag></tag>
   <elementGuidId>37944ac0-3923-44b1-a472-92d2e523b184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity_62cb6a08c79a4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_62cb6a08c79a4']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'number' and @class = 'input-text qty text' and @title = 'Qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1bb3a4e-b955-4d97-8a39-36d86ae06639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>93b770e2-c739-4b9e-a5ef-c018641797ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_62cb6a08c79a4</value>
      <webElementGuid>a8898308-b013-4417-9492-0f0e9fe7b7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>527ca590-2195-4666-90d6-be7d32674bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>65692745-0748-44e8-96b3-958ed1861fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5729426-4376-414a-9630-1e307f54223a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[70efdf2ec9b086079795c442636b55fb][qty]</value>
      <webElementGuid>1de29365-e7af-4923-b9c0-d870840b7339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9e7dbf95-b1db-4534-85b4-8eeae2579845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>5a41402a-af88-4292-b40b-63e0153f81f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3653d47f-aef6-41db-bb75-7ffd3150abd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>2379d762-5277-42d4-9757-2657a2bba9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>38cd6b85-09bb-412d-9bec-ce58247a735a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_62cb6a08c79a4&quot;)</value>
      <webElementGuid>9663669a-e5d6-47ec-8d94-19ad4132e54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_62cb6a08c79a4']</value>
      <webElementGuid>7fb66db3-c064-4f18-b814-fa6924595329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-53']/div/div/form/table/tbody/tr/td[5]/div/input</value>
      <webElementGuid>353f34e8-1575-4465-a52f-e569d744696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>a3e8e55b-6106-43f1-9343-266c6c597888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_62cb6a08c79a4' and @name = 'cart[70efdf2ec9b086079795c442636b55fb][qty]' and @title = 'Qty']</value>
      <webElementGuid>7d69087d-163b-4431-821a-9a9e85b44b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
