<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_name</name>
   <tag></tag>
   <elementGuidId>28308dda-39b4-4df2-9484-d4044f414693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.product-name > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-53']/div/div/form/table/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;post-53&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-name&quot;]/a[1][count(. | //*[@href = 'https://kotakoki.wijaysali.my.id/product/beanie/']) = count(//*[@href = 'https://kotakoki.wijaysali.my.id/product/beanie/'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e66252ee-91a1-486c-9737-e1fbc5a9bf1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/product/beanie/</value>
      <webElementGuid>5f93262a-481a-403e-bd61-54a6cb0130c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beanie</value>
      <webElementGuid>1e3391ad-11ec-427d-ad7a-06835e462cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-53&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-name&quot;]/a[1]</value>
      <webElementGuid>ed4c16f2-8df6-4240-a8ec-ea1e5c4eb160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-53']/div/div/form/table/tbody/tr/td[3]/a</value>
      <webElementGuid>8968cb63-cf20-488a-8b94-d2c771ab3fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beanie')]</value>
      <webElementGuid>dce3a384-9c81-4e9b-becf-21a6d200fcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::a[2]</value>
      <webElementGuid>f29d25a2-7b3e-44f0-a35c-fca1616066e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/following::a[3]</value>
      <webElementGuid>f8675a25-368e-4508-b42c-3b5ea3329318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[4]/preceding::a[1]</value>
      <webElementGuid>6c9609c4-785a-4b55-ba3a-21f32ddbfc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beanie quantity'])[1]/preceding::a[1]</value>
      <webElementGuid>7bca070d-8def-4240-aca9-478076aa5e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beanie']/parent::*</value>
      <webElementGuid>35369a36-44d8-4dc1-bd76-9639fbec0bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://kotakoki.wijaysali.my.id/product/beanie/')])[2]</value>
      <webElementGuid>a0d4ec0d-5c4f-4e24-8784-7f09becf90c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>3845701e-3c11-493b-a011-774b5f170433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kotakoki.wijaysali.my.id/product/beanie/' and (text() = 'Beanie' or . = 'Beanie')]</value>
      <webElementGuid>385db7b9-c3e2-40fe-bf25-894a9c1f9471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
